import os
import sys
import json
import uuid
import base64
import openpyxl

def generate_report(template_type, data_json, output_dir):
    try:
        data = json.loads(data_json)
        
        root_dir = os.path.dirname(__file__)
        file_path = os.path.abspath(os.path.join(root_dir, '../assets/template.xlsm'))
        
        if not os.path.exists(file_path):
            raise Exception(f"Excel template not found at {file_path}")
        
        # Load workbook with openpyxl
        wb = openpyxl.load_workbook(file_path, data_only=False, keep_vba=False)
        uid = str(uuid.uuid4())[:8]
        
        if template_type == 'degerlendirme':
            ws = wb['DEĞERLENDİRME FORMU']
            
            students = data.get('students', [])
            
            # Left student
            if len(students) > 0:
                s1 = students[0]
                ws['D9'] = s1.get('ad_soyad', '')
                ws['D10'] = s1.get('sube', '')
                ws['D11'] = s1.get('ogrenci_no', '')
                ws['D12'] = s1.get('dal', '')
                ws['C46'] = s1.get('usta_ogretici_adi', '')
                ws['H46'] = s1.get('ogretmen_adi', '')
            else:
                ws['D9'] = ""
                ws['D10'] = ""
                ws['D11'] = ""
                ws['D12'] = ""
                ws['C46'] = ""
                ws['H46'] = ""
                
            # Right student
            if len(students) > 1:
                s2 = students[1]
                ws['Q9'] = s2.get('ad_soyad', '')
                ws['Q10'] = s2.get('sube', '')
                ws['Q11'] = s2.get('ogrenci_no', '')
                ws['Q12'] = s2.get('dal', '')
                ws['P46'] = s2.get('usta_ogretici_adi', '')
                ws['U46'] = s2.get('ogretmen_adi', '')
            else:
                ws['Q9'] = ""
                ws['Q10'] = ""
                ws['Q11'] = ""
                ws['Q12'] = ""
                ws['P46'] = ""
                ws['U46'] = ""
                
            out_base = f"degerlendirme_{uid}"
            
        elif template_type == 'ogretmen':
            ws_template = wb['ÖĞRETMEN RAPORU']
            students = data.get('students', [])
            
            if not students:
                students = [{}] # Boş bir tane üret
                
            first = True
            for i, student in enumerate(students):
                ws = wb.copy_worksheet(ws_template) if not first else ws_template
                ws.title = f"Rapor_{student.get('ad_soyad', f'Ogrenci_{i}')[:20].replace('/', '_')}"
                first = False
                
                ws['D7'] = student.get('ad_soyad', '')
                ws['D8'] = student.get('dal', '')
                ws['D9'] = student.get('sube', '')
                ws['D10'] = student.get('ogrenci_no', '')
                ws['D11'] = student.get('usta_ogretici_adi', '')
                ws['D12'] = student.get('isyeri_adresi', '')
                
                # F37 Koordinatör Öğretmen
                ws['F37'] = student.get('ogretmen_adi', '')
            
            out_base = f"ogretmen_{uid}"
            target_sheet = None # We already renamed them, keep all except DEĞERLENDİRME FORMU and original template if it was duplicated
            
            # Remove DEĞERLENDİRME FORMU and other unnecessary sheets
            for sheet_name in wb.sheetnames:
                if "Rapor_" not in sheet_name and sheet_name != ws_template.title:
                    try:
                        del wb[sheet_name]
                    except:
                        pass
            
            # If we copied sheets, the original template might have a different name, but we used the first one as template. So no need to delete ws_template if we renamed it.
            if not first and ws_template.title in wb.sheetnames and not ws_template.title.startswith("Rapor_"):
                try:
                    del wb[ws_template.title]
                except:
                    pass
            
        else:
            print("Unknown template type")
            sys.exit(1)
            
        # Delete other sheets to save space
        if template_type == 'degerlendirme':
            target_sheet = ws.title
            for sheet_name in wb.sheetnames:
                if sheet_name != target_sheet:
                    del wb[sheet_name]
                    
        xlsx_path = os.path.abspath(os.path.join(output_dir, f"{out_base}.xlsx"))
        
        wb.save(xlsx_path)
        
        result = {
            "pdf_file": "", # PDF not generated by this script anymore
            "xlsx_file": f"{out_base}.xlsx"
        }
        print(json.dumps(result))
        
    except Exception as e:
        print(f"ERROR: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python generate_reports.py <template_type> <data_base64> <output_dir>")
        sys.exit(1)
        
    t_type = sys.argv[1]
    
    try:
        d_json = base64.b64decode(sys.argv[2]).decode('utf-8')
    except Exception as e:
        print(f"ERROR: Base64 decode failed - {str(e)}")
        sys.exit(1)
        
    out_dir = sys.argv[3]
    
    generate_report(t_type, d_json, out_dir)
